# fly.toml app configuration file for aiprc simulator
# Name can be overridden at deploy time with: fly deploy -a <app-name>
app = "aiprc-sim"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    grace_period = "10s"
    interval = "10s"
    method = "GET"
    path = "/"
    protocol = "http"
    timeout = "2s"

[mounts]
  source = "data"
  destination = "/data"
